# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f14b835aec29d294ead9073fb3e1665e5c0e99b33558fe36418fca50007d524ef78d309232ffcd6a94989743a411b49607d85dc1aa88224703c5f5b99663b4a9

test:
  secret_key_base: 0fca169eecebc103a020628585d84c6bc6c6d4a609e1cd443845be0ec9f82f75e0ca5fc48cb17cf37177cbc12428d21c6f6005dabb17e8239e8e3b54ebf721fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
